package com.amx.jax.complaince;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ExRemittanceApplication generated by hbm2java
 */
@Entity
@Table(name = "EX_REMIT_TRNX")
public class RemittanceTransaction implements Serializable {

	/**
	 * 
	 **/
	private static final long serialVersionUID = 1L;

	private BigDecimal remittanceTransactionId;
	private BigDecimal documentFinanceYear;
	private BigDecimal documentNo;
	
	
	@Id
	@GeneratedValue(generator="ex_remittance_transaction_seq",strategy=GenerationType.SEQUENCE)
	@SequenceGenerator(name="ex_remittance_transaction_seq",sequenceName="EX_REMITTANCE_TRANSACTION_SEQ",allocationSize=1)
	@Column(name = "REMITTANCE_TRANSACTION_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRemittanceTransactionId() {
		return this.remittanceTransactionId;
	}
	public void setRemittanceTransactionId(BigDecimal remittanceTransactionId) {
		this.remittanceTransactionId = remittanceTransactionId;
	}
	
	@Column(name = "DOCUMENT_FINANCE_YEAR")
	public BigDecimal getDocumentFinanceYear() {
		return documentFinanceYear;
	}
	public void setDocumentFinanceYear(BigDecimal documentFinanceYear) {
		this.documentFinanceYear = documentFinanceYear;
	}
	
	@Column(name = "DOCUMENT_NO")
	public BigDecimal getDocumentNo() {
		return documentNo;
	}
	public void setDocumentNo(BigDecimal documentNo) {
		this.documentNo = documentNo;
	}
	
	
	
	
	
	

}
 
