insert into JAX_CONDITIONAL_FIELD_RULE (ENTITY_NAME, FIELD_NAME, CONDITION_KEY, CONDITION_VALUE, JAX_COND_FIELD_RULE_SEQ_ID)
values ('BENEFICIARY', 'BENE_THIRD_NAME', 'bene-country-id', '95', 3);

insert into JAX_CONDITIONAL_FIELD_RULE (ENTITY_NAME, FIELD_NAME, CONDITION_KEY, CONDITION_VALUE, JAX_COND_FIELD_RULE_SEQ_ID)
values ('BENEFICIARY', 'BENE_FIRST_NAME', 'bene-country-id', '95', 1);

insert into JAX_CONDITIONAL_FIELD_RULE (ENTITY_NAME, FIELD_NAME, CONDITION_KEY, CONDITION_VALUE, JAX_COND_FIELD_RULE_SEQ_ID)
values ('BENEFICIARY', 'BENE_SECOND_NAME', 'bene-country-id', '95', 2);

insert into JAX_CONDITIONAL_FIELD_RULE (ENTITY_NAME, FIELD_NAME, CONDITION_KEY, CONDITION_VALUE, JAX_COND_FIELD_RULE_SEQ_ID)
values ('BENEFICIARY', 'BENE_FOURTH_NAME', 'bene-country-id', '95', 4);

insert into JAX_CONDITIONAL_FIELD_RULE (ENTITY_NAME, FIELD_NAME, CONDITION_KEY, CONDITION_VALUE, JAX_COND_FIELD_RULE_SEQ_ID)
values ('BENEFICIARY', 'BENE_FIFTH_NAME', 'bene-country-id', '95', 5);

insert into JAX_CONDITIONAL_FIELD_RULE (ENTITY_NAME, FIELD_NAME, CONDITION_KEY, CONDITION_VALUE, JAX_COND_FIELD_RULE_SEQ_ID)
values ('BENEFICIARY', 'BENE_FIRST_NAME_LOCAL', 'bene-country-id', '95', 6);

insert into JAX_CONDITIONAL_FIELD_RULE (ENTITY_NAME, FIELD_NAME, CONDITION_KEY, CONDITION_VALUE, JAX_COND_FIELD_RULE_SEQ_ID)
values ('BENEFICIARY', 'BENE_SECOND_NAME_LOCAL', 'bene-country-id', '95', 7);

insert into JAX_CONDITIONAL_FIELD_RULE (ENTITY_NAME, FIELD_NAME, CONDITION_KEY, CONDITION_VALUE, JAX_COND_FIELD_RULE_SEQ_ID)
values ('BENEFICIARY', 'BENE_THIRD_NAME_LOCAL', 'bene-country-id', '95', 8);

insert into JAX_CONDITIONAL_FIELD_RULE (ENTITY_NAME, FIELD_NAME, CONDITION_KEY, CONDITION_VALUE, JAX_COND_FIELD_RULE_SEQ_ID)
values ('BENEFICIARY', 'BENE_FOURTH_NAME_LOCAL', 'bene-country-id', '95', 9);

insert into JAX_CONDITIONAL_FIELD_RULE (ENTITY_NAME, FIELD_NAME, CONDITION_KEY, CONDITION_VALUE, JAX_COND_FIELD_RULE_SEQ_ID)
values ('BENEFICIARY', 'BENE_FIFTH_NAME_LOCAL', 'bene-country-id', '95', 10);

Commit;
/