insert into JAX_FIELD_REGEX_MAPPING (FIELD_NAME, REGEX_KEY)
values ('BENE_FIRST_NAME', 'ALPHABETS_1');

insert into JAX_FIELD_REGEX_MAPPING (FIELD_NAME, REGEX_KEY)
values ('BENE_FOURTH_NAME', 'ALPHABETS_1');

insert into JAX_FIELD_REGEX_MAPPING (FIELD_NAME, REGEX_KEY)
values ('BENE_SECOND_NAME', 'ALPHABETS_1');

insert into JAX_FIELD_REGEX_MAPPING (FIELD_NAME, REGEX_KEY)
values ('BENE_THIRD_NAME', 'ALPHABETS_1');

insert into JAX_FIELD_REGEX_MAPPING (FIELD_NAME, REGEX_KEY)
values ('BENE_FIFTH_NAME', 'ALPHABETS_1');

insert into JAX_FIELD_REGEX_MAPPING (FIELD_NAME, REGEX_KEY)
values ('BENE_FIRST_NAME_LOCAL', 'ARABIC_NAME');

insert into JAX_FIELD_REGEX_MAPPING (FIELD_NAME, REGEX_KEY)
values ('BENE_SECOND_NAME_LOCAL', 'ARABIC_NAME');

insert into JAX_FIELD_REGEX_MAPPING (FIELD_NAME, REGEX_KEY)
values ('BENE_THIRD_NAME_LOCAL', 'ARABIC_NAME');

insert into JAX_FIELD_REGEX_MAPPING (FIELD_NAME, REGEX_KEY)
values ('BENE_FOURTH_NAME_LOCAL', 'ARABIC_NAME');

insert into JAX_FIELD_REGEX_MAPPING (FIELD_NAME, REGEX_KEY)
values ('BENE_FIFTH_NAME_LOCAL', 'ARABIC_NAME');

Commit;
/