variables:
  SONAR_URL: "https://sonar.amxremit.com"
  SONAR_LOGIN: "gitlab"
  SONAR_PASSWORD: "amx@123"

sonarqube_master_job:
  stage: test
  only:
    - master
  image: maven:3.3.9-jdk-8-alpine
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.password=$SONAR_PASSWORD