CREATE OR REPLACE VIEW JAX_VW_EMPLOYMENT_TYPE
(COMPONENT_DATA_ID,COMPONENT_ID,COMPONENT_CODE,DATA_DESC,LANGUAGE_ID)
 AS SELECT A.Component_Data_Id,A.Component_Id,A.Component_Code,B.Data_Desc,B.Language_Id 
 from Fs_Biz_Component_Data A,Fs_Biz_Component_Data_Desc B
 where A.Component_Data_Id = B.Component_Data_Id And A.Component_Id = 68
 and B.Language_Id = 1
And A.Active = 'Y';

CREATE OR REPLACE VIEW JAX_VW_PROFESSION_LIST
(COMPONENT_DATA_ID,COMPONENT_ID,COMPONENT_CODE,DATA_DESC,LANGUAGE_ID)
 AS SELECT A.Component_Data_Id,A.Component_Id,A.Component_Code,B.Data_Desc,B.Language_Id 
 from Fs_Biz_Component_Data A,Fs_Biz_Component_Data_Desc B
 where A.Component_Data_Id = B.Component_Data_Id And A.Component_Id = 4
 and B.Language_Id = 1
And A.Active = 'Y';

ALTER TABLE FS_CUSTOMER ADD ISSUE_DATE TIMESTAMP(6); 

ALTER TABLE FS_CUSTOMER ADD EXPIRY_DATE TIMESTAMP(6);


CREATE TABLE "FS_FIELD_LIST" 
   (	
   "FIELD_ID" NUMBER(10,0) NOT NULL ENABLE, 
   "TENANT" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NATIONALITY" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"REMIT_COUNTRY" VARCHAR2(40 BYTE), 
	"KEY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DETAILS" VARCHAR2(100 BYTE), 	
	"COMPONENT" VARCHAR2(20 BYTE), 
	 CONSTRAINT "FS_FIELD_LIST_PK" PRIMARY KEY ("FIELD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USRTAB"  ENABLE
   );


create or replace view JAX_VW_ADDRESS_DESC (Component_Data_Id,Component_Id,Component_Code,Data_Desc,Language_Id)
AS SELECT A.Component_Data_Id,A.Component_Id,A.Component_Code,B.Data_Desc,B.Language_Id 
 from Fs_Biz_Component_Data A,Fs_Biz_Component_Data_Desc B
 where A.Component_Data_Id = B.Component_Data_Id 
 And A.Component_Id in (67) 
 and B.Language_Id = 1
And A.Active = 'Y';