package com.amx.jax.dict;

public enum ResponseCode {
	
	//BANK of OMAN
	TIME_EXCEEDS_FOR_OTP("IPAY0200079","TIME_EXCEEDS_FOR_OTP"), 
	CARD_NOT_REGISTERED_FOR_OTP("IPAY0200085","CARD_NOT_REGISTERED_FOR_OTP"), 
	BIN_RANGE_NOT_ENABLED("IPAY0100207",""),
	INVALID_CARD_NUMBER_01("Invalid card number","Invalid card number"),
	INVALID_CARD_NUMBER_DN("IPAY0100119","Transaction denied due to invalid card number"),
	BRAND_NOT_ENABLED("IPAY0100126","Brand not enabled"),
	INAVLID_RESULT_CODE("IPAY0100134","Transaction denied due to invalid Result Code"),
	MERCHANT_ID_MISMATCH("IPAY0100129","Transaction denied due to Merchant ID mismatch"),
	TERMINALT_ID_MISMATCH("IPAY0100130","Transaction denied due to Terminal ID mismatch"),
	VALIDATE_ORG_TRANX("IPAY0100142","Problem occurred while validating original transaction"),
	UNABLE_PROCESS_TRANX("IPAY0100160","Unable to process the transaction"),
	TRANX_NOT_PROCESS_INVALID_CAVV("IPAY0100170","Transaction Not Processed due to invalid CAVV"),
	TRANX_DENIED_INVALID_UDF3("IPAY0100066","Transaction denied due to invalid UDF3"),
	TRANX_DENIED_INVALID_CVV("IPAY0100073","Transaction denied due to invalid CVV"),
	TRANX_DENIED_INVALID_EXPIRY_YEAR("IPAY0100075","Transaction denied due to invalid expiry year"),
	TRANX_DENIED_INVALID_EXPIRY_MONTH("IPAY0100077","Transaction denied due to invalid expiry month"),
	TRANX_DENIED_INVALID_EXPIRY_DAY("IPAY0100079","Transaction denied due to invalid expiry day"),
	CARD_HOLDERNAME_NOT_PRESENT("IPAY0100081","Card holder name is not present"),
	EMPTY_OTP_NUMBER("IPAY0100092","Empty OTP number"),
	INVALID_OTP_NUMBER("IPAY0100093","Invalid OTP number"),
	TERMINAL_INACTIVE("IPAY0100095","Terminal inactive"),
	OTP_TRIES_EXCEED("IPAY0200075","OTP Tries Exceeded"),
	DUP_RECORD_TRANX_ID_EXIST("IPAY0100114","Duplicate Record, transaction ID already exist"),
	TRANX_DN_DUE_ORIGIN_TRANX_ID("IPAY0100115","Transaction denied due to missing original transaction id"),
	TRANX_DN_DUE_INVALID_TRANX_ID("IPAY0100116","Transaction denied due to invalid original transaction id"), 
	INVALID_CARD_NUMBER_03("IPAY0100118","Transaction denied due to card number length error"), 
	TRANX_DN_INVALID_PAY_INS("IPAY0100120","Transaction denied due to invalid payment instrument"),
	INVALID_CARD_NUMBER_04("IPAY0100121","Transaction denied due to invalid card holder name"),
	TRANX_DN_INVALID_ADDRESS("IPAY0100122","Transaction denied due to invalid address"),
	TRANX_DN_INVALID_POSTCODE("IPAY0100123","Transaction denied due to invalid postal code"),
	PROBLEM_VALID_TRANX("IPAY0100124","Problem occurred while validating transaction data"), 
    PAY_INS_NOT_ENABLED("IPAY0100125","Payment instrument not enabled"),
    TRANX_DN_INS_ID_MISMATCH("IPAY0100128","Transaction denied due to Institution ID mismatch"),
    TRANX_PAY_INS_MISMATCH("IPAY0100131","Transaction denied due to Payment Instrument mismatch"),
    TRANX_DN_CURRENCY_MISMATCH("IPAY0100132","Transaction denied due to Currency Code mismatch"),
    INVALID_CARD_NUMBER_05("IPAY0100133","Transaction denied due to Card Number mismatch"),
    PROBLEM_OCCURRED_PERFORM_ACTION("IPAY0100135","Problem occurred while doing perform action code reference id"),
    PROBLEM_OCCURRED_DEFAULT_INS("IPAY0200028","Problem occurred while loading default institution configuration"),
    TRANX_DN_PRV_CAPTUTRE_FAILURE("IPAY0100136","Transaction denied due to previous capture check failure"),
    TRANX_DN_CAPTURE_AMOUNT_FAILURE("IPAY0100138","Transaction denied due to capture amount versus auth amount check failure"),
    TRANX_DN_VOID_AMOUNT_FAILURE("IPAY0100139","Transaction denied due to void amount versus original amount check failure"),
    TRANX_DN_PRV_VOID_FAILURE("IPAY0100140","Transaction denied due to previous void check failure"),
    TRANX_DN_AUTH_ALREADY_CAPTURE("IPAY0100141","Transaction denied due to authorization already captured"),
    PROBLEM_OCCURRED_VAL_ORG_TRANX("IPAY0100142","Problem occurred while validating original transaction"), 
    NO_EXT_CONN_DEATILS_01("IPAY0200030","No external connection details for Extr Conn id"),
    NO_EXT_CONN_DEATILS_02("IPAY0200031","Alternate external connection details not found for the alt Extr Conn id"), 
    TRANX_ACTION_NULL("IPAY0100143","Transaction action is null"), 
    ISO_MSG_NULL("IPAY0100144","ISO MSG is null. See log for more details!"), 
    PROBLEM_OCCURRED_DEFAULT_MSG("IPAY0100145","Problem occurred while loading default messages in ISO Formatter"), 
    PROBLEM_OCCURRED_FORMT_PURCH_RQT("IPAY0100147","Problem occurred while formatting purchase request in B24 ISO Message Formatter"), 
    PROBLEM_OCCURRED_FORMT_RVRS_RQT("IPAY0100150","Problem occurred while formatting Reverse purchase request in B24 ISO Message Formatter"), 
    PROBLEM_OCCURRED_FORMT_AUTH_RQT("IPAY0100152","Problem occurred while formatting authorization request in B24 ISO Message Formatter"),
    PROBLEM_OCCURRED_FORMT_CAP_RQT("IPAY0100153","Problem occurred while formatting Capture request in B24 ISO Message Formatter"), 
    PROBLEM_OCCURRED_FORMT_RVRS_AUTH_RQT("IPAY0100155","Problem occurred while formatting reverse authorization request in B24 ISO Message Formatter"), 
    PROBLEM_OCCURRED_FORMT_RVRS_CAP_RQT("IPAY0100156","Problem occurred while formatting Reverse Capture request in B24 ISO Message Formatter"), 
    EXT_MSG_SYS_ERR("IPAY0100159","External message system error"), 
    UNABLE_TO_TRANX("IPAY0100160","Unable to process the transaction"), 
    PROBLEM_OCCURRED_TRANX("IPAY0100163","Problem occurred during transaction"),
    TRANX_NOT_PROCESS_EMPTY_AUTH_STS("IPAY0100166","Transaction Not Processed due to Empty Authentication Status"), 
    TRANX_NOT_PROCESS_INVALID_AUTH_STS("IPAY0100167","Transaction Not Processed due to Invalid Authentication Status"),   
    TRANX_NOT_PROCESS_EMPTY_ENRL_STS("IPAY0100168","Transaction Not Processed due to Empty Enrollment Status"), 
    TRANX_NOT_PROCESS_INVALID_ENRL_STS("IPAY0100169","Transaction Not Processed due to Invalid Enrollment Status"),   
    TRANX_NOT_PROCESS_EMPTY_CAVV("IPAY0100171","Transaction Not Processed due to Empty CAVV"), 
    PROBLEM_OCCURRED_CONV_AMT( "IPAY0100172","Problem occurred while converting amount"), 
    PROBLEM_OCCURRED_BUILD_RFND_RQT("IPAY0100173","Problem occurred while building refund request"),   
    PROBLEM_OCCURED_RFND_PROC("IPAY0100175","Problem occurred in refund process"), 
    PROBLEM_OCCURRED_PAY_DETAILS("IPAY0200009","Problem occurred while getting payment details"), 
    PAY_DETAILS_MISSING("IPAY0100041","Payment details missing"), 
    TRANX_TIME_LMT_EXCEEDS("IPAY0100042","Transaction time limit exceeds"), 
    PROBLEM_OCCURRED_IP_BLOCK("IPAY0200011","Problem occurred while getting IP block details"), 
    IP_ADDR_BLOCK_ALREADY("IPAY0100043","IP address is blocked already"), 
    PROBLEM_OCCUR_LOAD_PAY_PAGE("IPAY0100044","Problem occurred while loading payment page"),   
    DN_BY_RISK("IPAY0100045","Denied by Risk"), 
    PROBLEM_OCCUR_UPDATE_DSC_PAY_LOG("IPAY0200013","Problem occurred while updating description details in payment log"), 
    PAY_PAGE_VALID_FAILED_INVLD_STS("IPAY0100047","Payment Page validation failed due to invalid Order Status"), 
    TRANX_DECLN_EXCEED_OTP_ATTMPT("IPAY0100049","Transaction declined due to exceeding OTP attempts"), 
    PROBLEM_OCCUR_TRM_DETAILS("IPAY0200015","Problem occurred while getting terminal details"), 
    INVALID_TRM_KEY("IPAY0100050","Invalid terminal key"), 
    MISSING_TRM_KEY("IPAY0100051","Missing terminal key"), 
    PROBLEM_OCCUR_PROCESS_DRT_DEBIT("IPAY0100053","Problem occurred while processing direct debit"),  
    PAY_DETAILS_NOT_AVAL("IPAY0100054","Payment details not available"), 
    INS_NOT_ALLOW_TRM_BRND("IPAY0100056","Instrument not allowed in Terminal and Brand"), 
    PROBLEM_OCCUR_PAY_INS("IPAY0200016","Problem occurred while getting payment instrument"),
    PROBLEM_OCCUR_TRANX_DETAILS("IPAY0200018","Problem occurred while getting transaction details"), 
    TRANX_DN_INVALID("IPAY0100057","Transaction denied due to invalid processing option action code"), 
    TRANX_DN_INLD_INS("IPAY0100058","Transaction denied due to invalid instrument"), 
    TRANX_DN_INLD_CURR_CODE("IPAY0100059","Transaction denied due to invalid currency code"), 
    TRANX_DN_MISSING_AMT("IPAY0100060","Transaction denied due to missing amount"),
    TRANX_DN_INVLD_AMT("IPAY0100061","Transaction denied due to invalid amount"), 
    TRANX_DN_INVLD_CURR("IPAY0100062","Transaction denied due to invalid Amount/Currency"),
    TRANX_DN_INVLD_TRACK_ID("IPAY0100063","Transaction denied due to invalid track ID"),   
    TRANX_DN_INVLD_UDF1("IPAY0100064","Transaction denied due to invalid UDF1"),
    TRANX_DN_INVLD_UDF2("IPAY0100065","Transaction denied due to invalid UDF2"),
    TRANX_DN_INVLD_UDF3("IPAY0100066","Transaction denied due to invalid UDF3"),
    TRANX_DN_INVLD_UDF4("IPAY0100067","Transaction denied due to invalid UDF4"),
    TRANX_DN_INVLD_UDF5("IPAY0100068","Transaction denied due to invalid UDF5"),
    MISSING_PAY_INS("IPAY0100069","Missing payment instrument"), 
    TRANX_DN_FAILED_CARD_DIGIT_CAL("IPAY0100070","Transaction denied due to failed card check digit calculation"),
    TRANX_DN_MISSING_CVD2("IPAY0100071","Transaction denied due to missing CVD2"),
    TRANX_DN_INVLD_CVD2("IPAY0100072","Transaction denied due to invalid CVD2"),
    TRANX_DN_EXP_DATE("IPAY0100080","Transaction denied due to expiration date"),
    CARD_HOLDER_NOT_PRESENT("IPAY0100081","Card holder name is not present"),
    CARD_ADDR_NOT_PRESENT("IPAY0100082","Card address is not present"),
    CARD_POST_CODE_NOT_PRST("IPAY0100083","Card postal code is not present"), 
    TRANX_DN_MISSING_CVV("IPAY0100086","Transaction denied due to missing CVV"),
    TRM_ACTION_NOT_ENABLED("IPAY0100098","Terminal Action not enabled for Transaction request, Terminal"), 
    TRM_PAY_INS_NOT_ENABLED("IPAY0100099","Terminal Payment Instrument not enabled for Transaction request, Terminal"),
    PROBLEM_OCCUR_AUTH("IPAY0100100","Problem occurred while authorize"),  
    PROBLEM_OCCUR_RISK_PROFILE("IPAY0200019","Problem occurred while getting risk profile details"),
    DN_RISK_MAX_LIMIT("IPAY0100102","Denied by risk : Maximum Floor Limit Check - Fail"), 
    TRANX_DN_RISK_MAX_CONT("IPAY0100103","Transaction denied due to Risk : Maximum transaction count"),
    TRANX_DN_RISK_MAX_AMT("IPAY0100104","Transaction denied due to Risk : Maximum processing amount"),   
    PROBLEM_OCCUR_CURR("IPAY0200022","Problem occurred while getting currency"),
    INVLD_PAY_INS("IPAY0100106","Invalid payment instrument"), 
    PROBLEM_OCCUR_BRAND_RULE("IPAY0200024","Problem occurred while getting brand rules details"),   
    INS_NOT_ENABLED("IPAY0100107","Instrument not enabled"),  
    INVLD_TRANX_PAY_NULL("IPAY0100109","Invalid subsequent transaction, payment id is null or empty"), 
    PROBLEM_OCCUR_TRANX_LOG_DETAILS("IPAY0200026","Problem occurred while getting transaction log details"),
    MISSING_ENCRYPT_CARD_NUMBER("IPAY0200027","Missing encrypted card number"),    
    CARD_DECRYPT_FAIL("IPAY0100111","Card decryption failed"),  
    SUBSEQ_TRANX_ORGN_INVLD("IPAY0100113","subsequent transaction, but original transaction id is invalid"),
    MISSING_CURR("IPAY0100021","Missing currency"), 
    INVALID_AMOUNT("IPAY0100024","Invalid amount"),   
    INAVLID_TRACK_ID("IPAY0100027","Invalid track id"),   
    INVALID_USER_DEF_FIELD3("IPAY0100030","Invalid user defined field3"),     
    PROBLEM_OCCUR_VAL_PAY_DEATILS("IPAY0200007","Problem occurred while validating payment details"), 
    PROBLEM_OCCUR_PAY_DETAILS("IPAY0200008","Problem occurred while verifying payment details"), 
    PAY_ID_MISSING("IPAY0100037","Payment id missing"), 
    TRANX_PROG_TAB("IPAY0100040","Transaction in progress in another tab/window"),  
    PROBLEM_OCCUR_UPDT_PAY_DETAILS("IPAY0200010","Problem occurred while updating payment details"),
    PROBLEM_OCCUR_PAY_LOG_ID("IPAY0200012","Problem occurred while updating payment log IP details"),   
    PAY_OPTION_NOT_ENABLED("IPAY0100046","Payment option not enabled"),    
    CANCELLED("IPAY0100048","Cancelled"),
    PROBLEM_OCCUR_MERCH_RESPONSE("IPAY0200014","Problem occurred during merchant response"),

    PROBLEM_OCCUR_MERCH_RESP_ENCRYPT("IPAY0100052","Problem occurred during merchant response encryption"), 
    INVLD_PAY_STATUS("IPAY0100055","Invalid Payment Status"),
    PROBLEM_OCCUR_PAY_INS_LST("IPAY0200017","Problem occurred while getting payment instrument list"),    
    SORRY_INS_NOT_HANDLE("IPAY0100094","Sorry, this instrument is not handled"),  
    DN_RISK_PROF_NOT_EXIST("IPAY0100101","Denied by risk : Risk Profile does not exist"), 
    PROBLEM_OCCUR_PROFM_TRANX("IPAY0200020","Problem occurred while performing transaction risk check"), 
    PROBLEM_OCCUR_PROF_RISK("IPAY0200021","Problem occurred while performing risk check"), 
    PROBLEM_OCCUR_DETM_PAY_INS("IPAY0200023","Problem occurred while determining payment instrument"),
    PERFORM_RISK_CHECK_FAIL("IPAY0100108","Perform risk check : Failed"), 
    INVLD_SUBQ_TRANX_NULL_EMPTY("IPAY0100110","Invalid subsequent transaction, Tran Ref id is null or empty"),
    PROBLEM_OCCUR_ORGIN_TRANX("IPAY0100112","Problem occurred in method loading original transaction data(card number, exp month / year)"),
    TRANX_DN_MISSING_CARD_NUMBER("IPAY0100117","Transaction denied due to missing card number"),
    TRANX_DN_AMT_AUTH_CHECK_FAILURE("IPAY0100137","Transaction denied due to refund amount greater than auth amount check failure"),  
    PROBLEM_OCCUR_EXT_CONN("IPAY0200029","Problem occurred while getting external connection details"),   
    PROBLEM_OOCCUR_EXT_CONN_DETAILS("IPAY0200032","Problem occurred while getting external connection details for Extr Conn id"),  
    PROBLEM_OCCUR_FORMT_REFUND("IPAY0100151","Problem occurred while formatting Refund request in B24 ISO Message Formatter"), 
    PROBLEM_OCCUR_REVRS_MSG_FORMT("IPAY0100154","Problem occurred while formatting Reverse Refund request in B24 ISO Message Formatter"),
    HOST_TIMEOUT("IPAY0100158","Host (SWITCH) timeout"),    
    MRCH_NOT_ALLOW_ENCRYPT_PROC("IPAY0100161","Merchant is not allowed for encryption process"), 
    DECRPTY_TRANX_DATA_FAILED("IPAY0100176","Decrypting transaction data failed"), 
    INVALID_INPUT_DATA_REC("IPAY0100177","Invalid input data received"),   
    MRCH_ENCRPYT_ENABLED("IPAY0100178","Merchant encryption enabled"),  
    IVR_NOT_ENABLED("IPAY0100179","IVR not enabled"),
    AUTH_NOT_AVAL("IPAY0100180","Authentication not available"),
    CARD_ENCRPTY_FAIL("IPAY0100181","Card encryption failed"), 
    ERR_OCCUR_MRCH_ID("IPAY0200037","Error occurred while getting Merchant ID"),  
    ENCRPTY_ENABLED("IPAY0100186","Encryption enabled"), 
    TRANX_DN_BRAND_DIRC("IPAY0100189","Transaction denied due to brand directory unavailable"),  
    TRANX_DN_RISK_MAX("IPAY0100190","Transaction denied due to Risk : Maximum transaction count"),    
    DN_RISK_NEG_CARD("IPAY0100191","Denied by risk : Negative Card check - Fail"),     
    TRANX_NOT_PROC_EMPTY("IPAY0100192","Transaction Not Processed due to Empty XID "),
    TRANX_NOT_PROC_INVALID_XID("IPAY0100193","Transaction Not Processed due to invalid XID"),
    ERR_OCCUR_DTR_PAY_INS("IPAY0100202","Error occurred in Determine Payment Instrument"), 
    TRANX_DN_RISK_MIN_TRANX("IPAY0100194","Transaction denied due to Risk : Minimum Transaction Amount processing"),
    TRANX_DN_RISK_MAX_REFND_PROC("IPAY0100195","Transaction denied due to Risk : Maximum refund processing amount"), 
    TRANX_DN_RISK_MAX_PROC_AMT("IPAY0100196","Transaction denied due to Risk : Maximum processing amount"), 
    TRANX_DN_MAX_DBT_AMT("IPAY0100197","Transaction denied due to Risk : Maximum debit amount"),  
    TRANX_DN_RISK_TRANX_CNT_LMT("IPAY0100198","Transaction denied due to Risk : Transaction count limit exceeded for the IP"), 
    TRANX_DN_PRV_CHECK_FAILURE("IPAY0100199","Transaction denied due to previous refund check failure ( Validate Original Transaction"),

    PROBLEM_OCCUR_PERFORM_RISK_CHECK("IPAY0100246","Problem occurred while doing perform ip risk check"),
    MRCH_RES_URL_DWN("IPAY0100249","Merchant response url is down"),
    PAY_DETAILS_VERF_FAILURE("IPAY0100250","Payment details verification failed"), 
    INVALID_PAY_DATA("IPAY0100251","Invalid payment data"),  
    PROBLEM_OCCUR_CANCEL_TRANX("IPAY0100253","Problem occurred while cancelling the transaction"),   
    MERCH_NOT_ENABLED("IPAY0100254","Merchant not enabled"),   
    EXT_CONN_NOT_ENABLED("IPAY0100255","External connection not enabled"),   
    PAY_ENCRPYT_FAIL("IPAY0100256","Payment encryption failed"),   
    BRAND_RULE_NOT_ENABLE("IPAY0100257","Brand rules not enabled"),   
    PAY_OPT_NOT_ENABLE("IPAY0100260","Payment option(s) not enabled"),
    
    DN_RISK_NEG_BIN("IPAY0100200","Denied by risk : Negative BIN check - Fail"), 
    DN_RISK_DECL_CARD("IPAY0100201","Denied by risk : Declined Card check – Fail"),  
    PROBLEM_OCCUR_PRFM_TRANX("IPAY0100203","Problem occurred while doing perform transaction"), 
    MISSING_PAY_DETAILS("IPAY0100204","Missing payment details"), 
    PROBLEM_OCCUR_CURR_MINOR("IPAY0100206","Problem occurred while getting currency minor digits"), 
    ACTION_NOT_ENABLED("IPAY0100208","Action not enabled"),   
    INST_CONFIG_NOT_ENABLED("IPAY0100209","Institution config not enabled"), 
    PROBLEM_OCCUR_PROC_TRANX("IPAY0100213","Problem occurred while processing the hosted transaction request"),
    PROBLEM_OCCUR_VER_TRAN("IPAY0100214","Problem occurred while verifying tranportal id"), 
    INVLD_TRAN_ID("IPAY0100215","Invalid tranportal id"),    
    INVLD_DATA_REC("IPAY0100216","Invalid data received"),
    INVLD_PAY_DETAILS("IPAY0100217","Invalid payment detail"), 
    INVLD_BRAND_ID("IPAY0100218","Invalid brand id"),
    MISSING_CARD_NUMBER("IPAY0100219","Missing card number"), 
    INVLD_CARD_NUMBER("IPAY0100220","Invalid card number"),   
    MISSING_CARD_HLD_NAME("IPAY0100221","Missing card holder name"),
    INVLD_CARD_HLD_NAME("IPAY0100222","Invalid card holder name"), 
    MISSING_CVV("IPAY0100223","Missing cvv"), 
    INVALID_CVV("IPAY0100224","Invalid cvv"),
    MISSING_CARD_EXPY_YR("IPAY0100225","Missing card expiry year"),  
    INVALID_CARD_EXPY_YR("IPAY0100226","Invalid card expiry year"),
    MISSING_CARD_EXPY_MON("IPAY0100227","Missing card expiry month"),    
    INVALID_CARD_EXPY_MON("IPAY0100228","Invalid card expiry month"),     
    INVALID_CARD_EXPY_DAY("IPAY0100229","Invalid card expiry day"),     
    CARD_EXPIRED_01("IPAY0100230","Card expired"),     
    INVALID_USER_DEFINE_FIELD("IPAY0100231","Invalid user defined field"),     
    MISSING_ORG_TRANX_ID("IPAY0100232","Missing original transaction id"),    
    INVLD_ORGN_TRANX_ID("IPAY0100233","Invalid original transaction id"),
    PROBLEM_OCCUR_FORMAT_REVRS_REQ("IPAY0100234","Problem occurred while formatting Reverse completion request in ISO Message Formatter"), 
    PROBLEM_OCCUR_FORMAT_REVRS_REFUND_REQ("IPAY0100235","Problem occurred while formatting Reverse refund request in ISO Message Formatter"), 
    PROBLEM_OCCUR_FORMT_ISO_MSG("IPAY0100236","Problem occurred while formatting Capture request in ISO Message Formatter"), 
    PROBLEM_OCCUR_FORMT_PURCH_REQ("IPAY0100237","Problem occurred while formatting Reverse purchase request in ISO Message Formatter"),
    PROBLEM_OCCUR_FORMT_CAP_REQ("IPAY0100238","Problem occurred while formatting Capture request in ISO Message Formatter"),  
    PROBLEM_OCCUR_FORMT_AUTH_REQ("IPAY0100239","Problem occurred while formatting authorization request in ISO Message Formatter"), 
    PROBLEM_OCCUR_FORMT_RFND_REQ("IPAY0100240","Problem occurred while formatting refund request in ISO Message Formatter"), 
    PROBLEM_OCCUR_PURCH_REQ("IPAY0100241","Problem occurred while formatting purchase request in ISO Message Formatter"),    
    NOT_SUPP_PAY_INS("IPAY0100243","NOT SUPPORTED IPAY0100244 Payment Instrument Not Configured"),     
    PROBLEM_OCCUR_ISO_MSG("IPAY0100245","Problem occurred while sending/receiving ISO message"), 

    INVLD_TERMINAL("IPAY0100017","Inactive terminal"), 
    INVLD_LOG_IN_ATTMPT("IPAY0100019","Invalid log in attempt"),
    MISSING_ERROR_URL("IPAY0100001","Missing error URL"),
    INVLD_ERR_URL("IPAY0100002","Invalid error URL"),
    MISSING_RES_URL("IPAY0100003","Missing response URL"), 
    INVLD_RES_URL("IPAY0100004","Invalid response URL"),  
    MISSING_TRANPT_ID("IPAY0100005","Missing tranportal id"),
    INVLD_TRANPT_ID("IPAY0100006","Invalid tranportal ID"),
    MISSING_TGRANS_DATA("IPAY0100007","Missing transaction data"), 
    TERMINL_NOT_ENABLED("IPAY0100008","Terminal not enabled"), 
    PROBLEM_OCCUR_TERMINL("IPAY0200001","Problem occurred while getting terminal"), 
    INST_NOT_ENABLED("IPAY0100009","Institution not enabled"),
    PROBLEM_OCCUR_INS_DFEATILS("IPAY0200002","Problem occurred while getting institution details"), 
    INS_NOT_ENABLED_ENCYPT("IPAY0100010","Institution has not enabled for the encryption process"),
    PROBLEM_OCCUR_MRCHT_DETAILS("IPAY0200003","Problem occurred while getting merchant details"),
    MRCHT_NOT_ENABLED_ENCYPT_PROC("IPAY0100011","Merchant has not enabled for encryption process"),
    EMPPYT_TRML_KEY("IPAY0100012","Empty terminal key"),
    INVLD_TRANS_DATA("IPAY0100013","Invalid transaction data"), 
    TERMNL_AUTH_REQ_INVLD_TRANPT_ID("IPAY0100014","Terminal Authentication requested with invalid tranportal ID data"),
    INVLD_TRANPT_PASSWD("IPAY0100015","Invalid tranportal password"),
    PASSWD_SEC_NOT_ENABLED("IPAY0100016","Password security not enabled"), 
    PROBLEM_OCCUR_PASSWD_SEC("IPAY0200004","Problem occurred while getting password security rules"), 
    PROBLEM_OCCUR_UPDT_TERML("IPAY0200005","Problem occurred while updating terminal details"), 
    TERML_PASSWD_EXPRD("IPAY0100018","Terminal password expired"), 
    PROBLEM_OCCUR_VERFY_TRANPT("IPAY0200006","Problem occurred while verifying tranportal password"), 
    INVALID_ACTION_TYPE("IPAY0100020","Invalid action type"), 
    INVALID_CURRENCY("IPAY0100022","Invalid currency"),
    MISSING_AMOUNT("IPAY0100023","Missing amount"), 
    INVLD_AMT_CURR("IPAY0100025","Invalid amount or currency"), 
    INVLD_LANG_ID("IPAY0100026","Invalid language id"), 
    INVLD_USER_DEF_FD1("IPAY0100028","Invalid user defined field1"), 
    INVLD_USER_DEF_FD2("IPAY0100029","Invalid user defined field2"),
    INVLD_USER_DEF_FD4("IPAY0100031","Invalid user defined field4"),
    INVLD_USER_DEF_FD5("IPAY0100032","Invalid user defined field5"),
    TREMNL_ACTION_NOT_ENABLED("IPAY0100033","Terminal action not enabled"),
    CURR_CODE_NOT_ENABLE("IPAY0100034","Currency code not enabled"),
    PROBLEM_OCCUR_MRCHT_PROC("IPAY0100035","Problem occurred during merchant hashing process"), 
    UDF_MISMATCHED("IPAY0100036","UDF Mismatched"), 
    UNABLED_PROC_REQ("IPAY0100038","Unable to process the request"), 
    INVALID_PAY_ID("IPAY0100039","Invalid payment id"),

    
	//BANK of BENEFIT
    ISSUE_IN_CARD("05","The customer should contact the bank to resolve the Card issue"),
	INVALID_CARD_NUMBER("14","Invalid card number"),
    CARD_EXPIRED("33","The customer card is expired"),
	RESTRICTED_CARD("36","Restricted card"),
	PIN_EXCEED("38","Allowable PIN tries exceeded"),
    INSUFFICIENT_FUNDS("51","Insufficient funds"),
    CUSTOMER_CARD_EXPIRED("54","The customer card is expired"),
    INCORRECT_PIN_NUMBER("55","Incorrect pin number"),
    EXCEEDS_WITHDRAW_LIMIT("61","The card exceeds withdrawal amount limit"),
	RESTRICT_CARD("62","Restricted card"),
	EXCEEDS_WITHDRAW_FREQUENCY_LIMIT("65","Exceeds withdrawal frequency limit"),
	PIN_NUMBER_EXCEED("75","Allowable number PIN tries exceeded"),
	INELIGIBLE_ACCOUNT("76","Ineligible account"),
	REFER_ISSUE("78","Refer to Issuer"),
	BANK_DISCON("91","The bank is disconnected at the moment"),
	INVALID_CARD_NUMBER_02("PY20006","Invalid Brand");
    
    //Added for Testing
    //ERROR_TEST_92("92", "92 - Unmapped Declined for Testing");
    
	//public static final ResponseCode DEFAULT = RES_CODE_IPAY0200079;

	private String responseCode;
	private String responseDesc;
	
	ResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	ResponseCode(String responseCode,String responseDesc) {
		this.responseCode = responseCode;
		this.responseDesc = responseDesc;
	}

	public String getResponseCode() {
		return this.responseCode;
	}
	
	public String getResponseDesc() {
		return this.responseDesc;
	}
	
	// response code method added by Subodh
	public static ResponseCode getRespCodebyCode(String code) {
		ResponseCode[] allCodes = ResponseCode.values();
		for (ResponseCode respCode : allCodes) {
			if (respCode.getResponseCode().equals(code)){
				respCode.getResponseDesc();
				return respCode;
			}
		}
		return null;
	}

}
