insert into JAX_FIELD (NAME, REQUIRED, TYPE, DEFAULT_VALUE, MAX_LENGTH, MIN_LENGTH)
values ('BENE_THIRD_NAME', 'Y', 'text', '', 100, 1);

insert into JAX_FIELD (NAME, REQUIRED, TYPE, DEFAULT_VALUE, MAX_LENGTH, MIN_LENGTH)
values ('BENE_FOUR_NAME', 'Y', 'text', '', 100, 1);

insert into JAX_FIELD (NAME, REQUIRED, TYPE, DEFAULT_VALUE, MAX_LENGTH, MIN_LENGTH)
values ('BENE_SECOND_NAME', 'Y', 'text', '', 100, 1);

insert into JAX_FIELD (NAME, REQUIRED, TYPE, DEFAULT_VALUE, MAX_LENGTH, MIN_LENGTH)
values ('BENE_FIRST_NAME', 'Y', 'text', '', 100, 1);

insert into JAX_FIELD (NAME, REQUIRED, TYPE, DEFAULT_VALUE, MAX_LENGTH, MIN_LENGTH)
values ('BENE_FOURTH_NAME', 'Y', 'text', '', 100, 1);

insert into JAX_FIELD (NAME, REQUIRED, TYPE, DEFAULT_VALUE, MAX_LENGTH, MIN_LENGTH)
values ('BENE_FIFTH_NAME', 'Y', 'text', '', 100, 1);

insert into JAX_FIELD (NAME, REQUIRED, TYPE, DEFAULT_VALUE, MAX_LENGTH, MIN_LENGTH)
values ('BENE_FIRST_NAME_LOCAL', 'Y', 'text', '', 100, 1);

insert into JAX_FIELD (NAME, REQUIRED, TYPE, DEFAULT_VALUE, MAX_LENGTH, MIN_LENGTH)
values ('BENE_SECOND_NAME_LOCAL', 'Y', 'text', '', 100, 1);

insert into JAX_FIELD (NAME, REQUIRED, TYPE, DEFAULT_VALUE, MAX_LENGTH, MIN_LENGTH)
values ('BENE_THIRD_NAME_LOCAL', 'Y', 'text', '', 100, 1);

insert into JAX_FIELD (NAME, REQUIRED, TYPE, DEFAULT_VALUE, MAX_LENGTH, MIN_LENGTH)
values ('BENE_FOURTH_NAME_LOCAL', 'Y', 'text', '', 100, 1);

insert into JAX_FIELD (NAME, REQUIRED, TYPE, DEFAULT_VALUE, MAX_LENGTH, MIN_LENGTH)
values ('BENE_FIFTH_NAME_LOCAL', 'Y', 'text', '', 100, 1);

Commit;
/

