ALTER TABLE JAX_FIELD  ADD (LABEL VARCHAR2(100) );

Insert into JAX_FIELD (NAME,TYPE,DEFAULT_VALUE,REQUIRED,MIN_LENGTH,MAX_LENGTH,LABEL) values ('HEALTH CARD NUMBER','text',null,'Y',3,25,'Healthcard No');
Insert into JAX_FIELD (NAME,TYPE,DEFAULT_VALUE,REQUIRED,MIN_LENGTH,MAX_LENGTH,LABEL) values ('PAYMENT PERIOD FROM DATE','date','MM/DD/YYYY',null,null,null,'Healthcard From Date');
Insert into JAX_FIELD (NAME,TYPE,DEFAULT_VALUE,REQUIRED,MIN_LENGTH,MAX_LENGTH,LABEL) values ('PAYMENT PERIOD EXPIRY DATE','date','MM/DD/YYYY',null,null,null,'Healthcard To Date');
Insert into JAX_FIELD (NAME,TYPE,DEFAULT_VALUE,REQUIRED,MIN_LENGTH,MAX_LENGTH,LABEL) values ('ROUTING NUMBER','text',null,'Y',3,25,'Routing Number');

Insert into JAX_FIELD_REGEX_MAPPING (FIELD_NAME,REGEX_KEY) values ('HEALTH CARD NUMBER','ALPHANUMERIC');
Insert into JAX_FIELD_REGEX_MAPPING (FIELD_NAME,REGEX_KEY) values ('ROUTING NUMBER','ALPHANUMERIC');
commit;
