 CREATE OR REPLACE FORCE VIEW  "V_EX_COUNTRY_LANG" ("IDNO", "COUNTRY_NAME", "COUNTRY_ID", "LANGUAGE_ID", "NATIONALITY", "APPROVED_BY", "APPROVED_DATE", "BUSINESS_COUNTRY", "COUNTRY_ACTIVE", "COUNTRY_ALPHA2_CODE", "COUNTRY_ALPHA3_CODE", "COUNTRY_CODE", "COUNTRY_ISO_CODE", "COUNTRY_TEL_CODE", "CREATED_BY", "CREATED_DATE", "ISACTIVE", "SPLIT_INDICATOR", "DIRECTION", "LANGUAGE_CODE", "LANGUAGE_NAME", "COUNTRY_MOB_LENGTH") AS 
  SELECT  C.COUNTRY_DESC_ID  IDNO,
        C.COUNTRY_NAME         ,
        C.COUNTRY_ID           ,
        C.LANGUAGE_ID          ,
        C.NATIONALITY          ,
        D.APPROVED_BY          ,
        D.APPROVED_DATE        ,
        D.BUSINESS_COUNTRY     ,
        D.COUNTRY_ACTIVE       ,
        D.COUNTRY_ALPHA2_CODE  ,
        D.COUNTRY_ALPHA3_CODE  ,
        D.COUNTRY_CODE         ,
        D.COUNTRY_ISO_CODE     ,
        D.COUNTRY_TEL_CODE     ,
        D.CREATED_BY           ,
        D.CREATED_DATE         ,
        D.ISACTIVE             ,
        D.SPLIT_INDICATOR      ,
        L.DIRECTION            ,
        L.LANGUAGE_CODE        ,
        L.LANGUAGE_NAME        ,
        D.COUNTRY_MOB_LENGTH
FROM    FS_COUNTRY_MASTER_DESC C  ,
        FS_COUNTRY_MASTER D      ,
        FS_LANGUAGE_TYPE L
WHERE   C.COUNTRY_ID           =D.COUNTRY_ID
        AND C.LANGUAGE_ID      =L.LANGUAGE_ID
        AND D.COUNTRY_ACTIVE='Y'
ORDER BY D.COUNTRY_CODE ASC;