multitenancy:
    dataSourcesProps:
      -
        tenantId: 1
        url: jdbc:h2:file:~/test
        username: sa
        password: 
        driverClassName: org.h2.Driver
      -
        tenantId: 91
        url: jdbc:oracle:thin:@172.17.1.99:1522:TEMOS
        username: TEMOS
        password: TEMOS
        driverClassName: oracle.jdbc.OracleDriver