multitenancy:
    dataSourcesProps:
      -
        tenantId: 1
        url: jdbc:h2:file:~/test
        username: sa
        password: 
        driverClassName: org.h2.Driver
      -
        tenantId: KWT
        url: jdbc:oracle:thin:@10.28.42.10:1521:TEMOS
        username: TEMOS
        password: TEMOS
        driverClassName: oracle.jdbc.OracleDriver
      -
        tenantId: BHR
        url: jdbc:oracle:thin:@10.28.42.10:1521:TBHEMOS
        username: tbexchdba
        password: tbexchdba
        driverClassName: oracle.jdbc.OracleDriver
      -
        tenantId: OMN
        url: jdbc:oracle:thin:@10.28.42.10:1521:TMEX
        username: tmex
        password: tmex
        driverClassName: oracle.jdbc.OracleDriver
