package com.amx.jax.dbmodel.remittance;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ExRemittanceApplication generated by hbm2java
 */
@Entity
@Table(name = "EX_REMIT_TRNX")
public class RemittanceTransaction implements Serializable {

	/**
	 * 
	 **/
	private static final long serialVersionUID = 1L;

	private BigDecimal remittanceTransactionId;
	private BigDecimal documentNo;
	private BigDecimal documentFinancialyear;
	private BigDecimal applicationDocumentNo;
	private BigDecimal applicationdocumentFinancialyear;
	private BigDecimal collectionDocumentFinancialyear;
	private BigDecimal collectionDocumentNo;
	private BigDecimal customerId;
	private BigDecimal exchangeRateApplied;


	@Id
	@Column(name = "REMITTANCE_TRANSACTION_ID")
	public BigDecimal getRemittanceTransactionId() {
		return this.remittanceTransactionId;
	}

	public void setRemittanceTransactionId(BigDecimal remittanceApplicationId) {
		this.remittanceTransactionId = remittanceApplicationId;
	}

	@Column(name = "DOCUMENT_NO")
	public BigDecimal getDocumentNo() {
		return documentNo;
	}

	public void setDocumentNo(BigDecimal documentNo) {
		this.documentNo = documentNo;
	}

	@Column(name = "DOCUMENT_FINANCE_YEAR")
	public BigDecimal getDocumentFinancialyear() {
		return documentFinancialyear;
	}

	public void setDocumentFinancialyear(BigDecimal documentFinancialyear) {
		this.documentFinancialyear = documentFinancialyear;
	}

	@Column(name = "COLLECTION_DOC_FINANCE_YEAR")
	public BigDecimal getCollectionDocumentFinancialyear() {
		return collectionDocumentFinancialyear;
	}

	public void setCollectionDocumentFinancialyear(BigDecimal collectionDocumentFinancialyear) {
		this.collectionDocumentFinancialyear = collectionDocumentFinancialyear;
	}

	@Column(name = "COLLECTION_DOCUMENT_NO")
	public BigDecimal getCollectionDocumentNo() {
		return collectionDocumentNo;
	}

	public void setCollectionDocumentNo(BigDecimal collectionDocumentNo) {
		this.collectionDocumentNo = collectionDocumentNo;
	}

	@Column(name = "APPLICATION_DOCUMENT_NO")
	public BigDecimal getApplicationDocumentNo() {
		return applicationDocumentNo;
	}

	public void setApplicationDocumentNo(BigDecimal applicationDocumentNo) {
		this.applicationDocumentNo = applicationDocumentNo;
	}

	@Column(name = "APPLICATION_FINANCE_YEAR")
	public BigDecimal getApplicationdocumentFinancialyear() {
		return applicationdocumentFinancialyear;
	}

	public void setApplicationdocumentFinancialyear(BigDecimal applicationdocumentFinancialyear) {
		this.applicationdocumentFinancialyear = applicationdocumentFinancialyear;
	}

	@Column(name = "CUSTOMER_ID")
	public BigDecimal getCustomerId() {
		return customerId;
	}

	public void setCustomerId(BigDecimal customerId) {
		this.customerId = customerId;
	}

	@Column(name = "EXCHANGE_RATE_APPLIED")
	public BigDecimal getExchangeRateApplied() {
		return exchangeRateApplied;
	}

	public void setExchangeRateApplied(BigDecimal exchangeRateApplied) {
		this.exchangeRateApplied = exchangeRateApplied;
	}
}
