package com.amx.amxlib.constant;

public enum JaxFieldEntity {

	BENEFICIARY, FLEX_FIELD,CUSTOMERDETAILS,LOCALADDRESS,HOMEADDRESS,EMPOLOYEEDETAILS, REMITTANCE_ONLINE,AML_AUTH,PURPOSE_OF_TRNX,SERVICE_PROVIDER,BENEFICIARY_SWIFT_BANK1,
	BENEFICIARY_SWIFT_BANK2,INSTRUCTION;
	BENEFICIARY, FLEX_FIELD,CUSTOMERDETAILS,LOCALADDRESS,HOMEADDRESS,EMPOLOYEEDETAILS, REMITTANCE_ONLINE,AML_AUTH,PURPOSE_OF_TRNX,SERVICE_PROVIDER,BNFTELLAB;
}
