package com.amx.amxlib.constant;

public enum JaxTransactionStatus {

	PAYMENT_SUCCESS_APPLICATION_SUCCESS, PAYMENT_SUCCESS_APPLICATION_FAIL, PAYMENT_FAIL, PAYMENT_IN_PROCESS, APPLICATION_CREATED,
	PAYMENT_CANCELED_BY_USER;
}
