package com.amx.jax.grid;

public enum GridView {
	USER_SESSION_RECORD, USER_SESSION_RECORD_CUSTOM, USER_SESSION,
	VW_FS_EMPLOYEE, EX_BRANCH_SYSTEM_INVENTORY,

	DEVICE_CLIENT,

	VW_CUSTOMER_KIBANA, VW_KIBANA_TRNX, EX_V_RATE_PATTERN
}
