package com.amx.jax.constants;

public enum JaxFieldEntity {

	BENEFICIARY, FLEX_FIELD,CUSTOMERDETAILS,LOCALADDRESS,HOMEADDRESS,EMPOLOYEEDETAILS, REMITTANCE_ONLINE,AML_AUTH,PURPOSE_OF_TRNX,SERVICE_PROVIDER;
}
