package com.amx.jax.constants;

public enum JaxTransactionStatus {
    // error category codes START	
	CONN_FAILURE,
	FORMT_ERR,
	INST_ISSUES,
	LOG_NOT_FOUND,
	MRCH_ERR,PAYMENT_ERR,
	TERML_ERR,
	TXN_AUTH,
	TXN_BANK,
	TXN_CARD,
	TXN_DATA,
	TXN_DN_RISK,
	TXN_LIMIT,
	TXN_REFUND_ISSUE,
	TXN_REQ_FAILURE,
	TXN_SEC_FAILURE,
	TXN_SESSION,TXN_SUCCESS,
	TXN_TRNP,
	TXN_UDF,
	TXN_URL,
	TXN_AUTH_PIN,
	TXN_CANCEL_SUCC,
	TXN_CANCEL_FAIL,
	TXN_CARD_VLDT,
	TXN_DATA_CURR,
	TXN_LIMIT_FUNDS,
	TXN_OTP_LIM,
	TXN_OTP_VLDT,
	// error category codes END

	//this is only for jax	
    PAYMENT_SUCCESS_APPLICATION_SUCCESS, PAYMENT_SUCCESS_APPLICATION_FAIL, PAYMENT_FAIL, PAYMENT_IN_PROCESS, APPLICATION_CREATED,
    PAYMENT_CANCELED_BY_USER;
}
