package com.amx.jax.pricer.dbmodel;

import javax.persistence.Entity;
import javax.persistence.Table;

@Entity
@Table(name = "V_EX_DYN_ROUTING_MATRIX")
public class ViewExRoutingMatrix {

	/*APPLICATION_COUNTRY_ID	BENE_COUNTRY_ID	BENE_BANK_ID	BENE_BANK_BRANCH_ID	CURRENCY_ID	
	SERVICE_GROUP_CODE	COUNTRY_NAME	BANK_IND	BANK_CODE	BANK_FULL_NAME	ROUTING_COUNTRY_ID	
	ROUTING_BANK_CODE	ROUTING_BANK_ID	BANK_BRANCH_ID	SERVICE_MASTER_ID	SERVICE_DESCRIPTION	
	REMITTANCE_MODE_ID	REMITTANCE_DESCRIPTION	DELIVERY_MODE_ID	DELIVERY_DESCRIPTION	
	WEEK_FROM	WEEK_TO	WEEK_HOURS_FROM	WEEK_HOURS_TO	WEEKEND_FROM	WEEKEND_TO	WEEKEND_HOURS_FROM	
	WEEKEND_HOURS_TO	DELIVERY_MINUTES	TXN_AMT_FROM	TXN_AMT_TO	FROM_AMOUNT	TO_AMOUNT	CHARGES_TYPE	
	CHARGES_FOR	CHARGE_AMOUNT	COST_CURRENCY_ID	COST_AMOUNT	NO_BENE_DEDUCT_CHARGE_AMOUNT
	*/
	
	
	
}
